<div style="float: left">
    <h3>Receipts for Property : <?php echo $property->address; ?></h3>
</div>
<div style="float: right">
    <h3>Owner : <?php echo ucfirst($property->entry0->first_name) . ' ' . ucfirst($property->entry0->last_name); ?></h3>
</div>
<div class="clearfix"></div>
<div><input type="button" value="Add New Receipt" class="button" onclick="javascript:window.document.location.replace('<?php echo Yii::app()->request->baseUrl ?>/receipts/add/prop_id/<?php echo $property->id; ?>')"></div>
<?php
$dataProvider = new CActiveDataProvider('Receipt', array('criteria'=>array('condition'=> 'property_id = ' . $property->id, 'order'=>'id DESC'), 'pagination' => false));

$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'columns'=>array(
        array(
            'name' => 'Receipt Number',
            'value' => '$data->receipt_number',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Property Address',
            'value' => '$data->property_address',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Landlord',
            'value' => '$data->landlord_name',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Tenant',
            'value' => '$data->tenant_name',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Rent',
            'value' => '"$" . $data->rent',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Paid',
            'value' => '"$" . $data->paid',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'From Date',
            'value' => '$data->from_date',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'To Date',
            'value' => '$data->to_date',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Generated By',
            'value' => '$data->partner_name',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array(
            'name' => 'Generated Date',
            'value' => '$data->receipt_date',
            'headerHtmlOptions'=>array('style'=>'text-align:left;'),
        ),
        array
        (
            'class'=>'CButtonColumn',
            'deleteConfirmation'=>"js:'Are you sure you want to delete this Receipt ?'",
            'template'=>'{delete}{update}',
            'buttons'=>array(
                'delete' => array
                (
                    'options'=>array('style'=>'padding-right:25px'),
                ),
                'update' => array
                (
                    'url'=>'Yii::app()->request->baseUrl . "/receipts/add/prop_id/" . $data->property_id . "/receipt_id/" . $data->id'
                )
            )
        )
    )
));
?>