<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <style type="text/css">
        body {
            font-family: helvetica, verdana, sans-serif;
        }

        .grid-view
        {
            padding: 15px 0;
        }

        .grid-view table.items
        {
            background: white;
            border-collapse: collapse;
            width: 100%;
            border: 1px #D0E3EF solid;
        }

        .grid-view table.items th, .grid-view table.items td
        {
            font-size: 1.1em;
            border: 1px white solid;
            padding: 0.3em;
        }

        .grid-view table.items th
        {
            color: white;
            background: #5e94f3;
            text-align: center;
        }

        .grid-view table.items th a
        {
            color: #EEE;
            font-weight: bold;
            text-decoration: none;
        }

        .grid-view table.items th a:hover
        {
            color: #FFF;
        }

        .grid-view table.items tr.even
        {
            background: #F8F8F8;
        }

        .grid-view table.items tr.odd
        {
            background: #E5F1F4;
        }

        .grid-view table.items tr.selected
        {
            background: #BCE774;
        }

        .grid-view table.items tr:hover
        {
            background: #ECFBD4;
        }

        .grid-view .link-column img
        {
            border: 0;
        }

        .grid-view .button-column
        {
            text-align: center;
            width: 60px;
        }

        .grid-view .button-column img
        {
            border: 0;
        }

        .grid-view .checkbox-column
        {
            width: 15px;
        }

        .grid-view .summary
        {
            margin: 0 0 5px 0;
            text-align: right;
        }

        .grid-view .pager
        {
            margin: 5px 0 0 0;
            text-align: right;
        }

        .grid-view .empty
        {
            font-style: italic;
        }

        .grid-view .filters input,
        .grid-view .filters select
        {
            width: 100%;
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
    <div class="container" id="page" style="width: 98%; padding: 10px">
    <h1>Receipts Summary for Property : <?php echo $property->address; ?></h1>
    <h2>Date Range : From <?php echo $date_range['start_date']; ?> To <?php echo $date_range['end_date']; ?></h2>
    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'dataProvider'=>$dataProvider,
        'columns'=>array(
            array(
                'name' => 'Receipt Number',
                'value' => '$data->receipt_number',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Property Address',
                'value' => '$data->property_address',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Landlord',
                'value' => '$data->landlord_name',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Tenant',
                'value' => '$data->tenant_name',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Rent',
                'value' => '"$" . $data->rent',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Paid',
                'value' => '"$" . $data->paid',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'From Date',
                'value' => '$data->from_date',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'To Date',
                'value' => '$data->to_date',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Generated By',
                'value' => '$data->partner_name',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            ),
            array(
                'name' => 'Generated Date',
                'value' => '$data->receipt_date',
                'headerHtmlOptions'=>array('style'=>'text-align:left;'),
            )
        )
    ));
    ?>
    </div>
</body>
</html>